ecommerce_ecommerce:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing.yml"
    prefix:   /
ecommerce_ecommerce_admin:
    resource: "@EcommerceEcommerceBundle/Resources/config/admin.yml"
    prefix:   /admin/
app:
    resource: @AppBundle/Controller/
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"